#!/bin/bash

# mmm-bat, Copyright (C) 2013-2014 Jinseop Kim(vmfhrmfoaj@yahoo.com)
# mmm-bat comes with ABSOLUTELY NO WARRANTY; for details
# type LICENSE file.  This is free software, and you are welcome
# to redistribute it under certain conditions; type LICENSE
# for details.
# If the LICENSE file does not exist,
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

. mmm-bat.sh

#
# Variables
#

# configureations
BUILD_LOG_FILE="mmm.log"
CUR_DIR=$(pwd)
SCRIPT_FILE="push.bat"


#
# functions
#

function restoreCurDir() {
  cd ${CUR_DIR}
}

function main() {
  local target_path=$(getTargetPath "${CUR_DIR}/${1}")
  local product_name=${2:-$(predictProductName)}

  writeLog "---------------------------------------------------------------------"
  writeLog "Date: $(date)"
  writeLog "Product: ${product_name}"
  writeLog "Path: ${target_path}"

  build ${target_path} ${product_name} ${BUILD_LOG_FILE} ${SCRIPT_FILE}
}

function changeCurDirToAndroid
  local root_dir=$(getRootPath ${CUR_DIR})
  if [ ! -d ${root_dir} ]; then
    echo "Can not find the Android directory."
    echo "-  [DEBUG] cur_dir: \"${CUR_DIR}\""
    echo "-  [DEBUG] root_dir: \"${root_dir}\""
    exit -1
  fi
  cd ${root_dir}
}

changeCurDirToAndroid
main $1 $2 || restoreCurDir
restoreCurDir
